FORMAT: 1A
HOST: http://api.spiderlog.net

# Spider Log API

Provides services for Spider Log app family, recording the world's spider sightings

# Group Spiders
Access to Spider resources

## My Spiders [/spiders{?page,size}]
### Get all my spider sightings [GET]

+ Parameters
    + page (required, number) - page number
    + size (required, number)- page size
    
+ Request

    + Header
    
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
        
+ Response 200 (application/json)

    + Header
        cache-control: max-ago=600
        
    + Body

            {
                "page" : 
                {
                    "number" : 1,
                    "size" : 10,
                    "totalPages" : 20
                },
                "spiders" : 
                [
                    
                    {
                        "sightedAt" : "2016-08-29T19:00",
                        "imageUrl" : "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Huntsman_spider.jpg/619px-Huntsman_spider.jpg",
                        "description" : "Spider I saw at home",
                        "tags": [
                            "big",
                            "stripy"
                            ]
                    }, 
                    {
                        "sightedAt" : "2016-08-29T19:00",
                        "imageUrl" : "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Mouse_spider.jpg/800px-Mouse_spider.jpg",
                        "description" : "Spider I saw at the office",
                        "tags": [
                            "big"
                            ]
                    }, 
                    {
                        "sightedAt" : "2016-08-29T19:00",
                        "imageUrl" : "https://upload.wikimedia.org/wikipedia/en/0/01/Spider-man_man-spider.jpg",
                        "description" : "Spider I saw at train",
                        "tags": [
                            "big",
                            "stripy"
                            ]
                    }
                ]